### ISSUE TITLE
Trying to understand Watchers

### ISSUE THREAD

**Issue by jasongrishkoff** [ramezrafla/redis-oplog#13]
Just want to wrap my head around this...

If I'm using two devices -- a desktop and a phone -- from the same user account, does that mean that updating something in device #1 will not automatically flow through to device #2 unless I use Watchers?

**Comment by evolross** [comment]
No, you don't need Watchers to update a document and have two clients that are subscribed to that same document update (e.g. a user document). That happens by default with standard `redis-oplog` functionality (or Meteor's polling or native oplog-tailing functionality).

Watchers are for skipping a trip to the database. It uses Redis to send the same client updates _as if_ the document was updated via the database (how `redis-oplog` normally works). But it allows you to skip over the database part. So in essence, it's using the Mongo transactions (e.g. update, insert, remove) to update client copies of documents _without_ actually updating them in the database. Which can be useful. 

It's a way to "message" all clients directly without needlessly taking a round trip to the database, by updating some field for example, just to get your clients to update the document. It's only useful in some use-cases.

I prefer Vent from the original `redis-oplog` because you can send any kind of message you want on any channel. Versus tying it to a field update with Mongo transactions with Watchers.

**Comment by evolross** [comment]
One thing I am confused about after reading the documentation again is how is using `{skipDB:true}` different than Watchers? Seems like it's the same concept - document mutations that skip the DB but Redis delivers to collection observers (e.g. pub/sub thus client template helpers, autoruns)?

**Comment by evolross** [comment]
Any comment on my last question @ramezrafla?

**Comment by ramezrafla** [comment]
Sorry, I thought it was addressed
- `{skipDB:true}` allows us to send mutations to other Meteor instances (and relevant caches) for existing collections.
- Watchers sends data to other Meteor instances, except no collection or caching is involved

So it's more of a use-case issues
- `{skipDB:true}` allows temporary changes to one or more documents that you don't really care about reflecting in the database. Transitory data .. e.g. typing indicator that a user is typing to respond to a message in a chat
- Watchers sends data across Meteor instances that is NOT stored in a collection .. e.g. server-related information you are sending across to other servers, like the fact that you are about to run a cron job and don't want conflicts with other servers who may try to start the same job in parallel. Watchers is a communication channel between servers
