### ISSUE TITLE
reactivity issue

### ISSUE THREAD

**Issue by goyan** [ramezrafla/redis-oplog#24]
Hi,

we faced an issue when using this package in our blazed based, multi-service project.
When updating the user profile from the client side (hence using minimongo), we found no reactivity.
We fall back on /cult-of-coders/redis-oplog which seems to fix our main issue though (cpu issues).
Is updating from minimongo a supported use case? This seems related to race condition detection as increasing it to high value seems to resolve a bit the issue, but with 10s delay, this won't cut it for our users experience.
If you need more information, don't hesitate.
regards,
Hervé

**Comment by ramezrafla** [comment]
Hi @goyan 

Right now we don't have client-side mutations. We removed this feature on purpose when migrating from the original redis-oplog as it's a major security hole. As well, Meteor group strongly recommends against it and is kept for legacy reasons. 

If you can, dump the original redis-oplog as soon as you can, as it is falling in disrepair. The DB hits due to its inherent design is a killer once you scale a bit. Move away to method-based mutations as soon as you can.
